version: '2'
services:
  mongo:
    image: mongo
    expose:
      - "27017"
    volumes:
      - ./volumes/mongo:/data/db

  node:
    image: node:8-slim
    ports:
      - "3000:3000"
    volumes:
      - ./:/data
    working_dir: /data
    command: npx nodemon .
    depends_on:
      - mongo
